# Generated by Django 3.1.5 on 2021-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align_tap', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
