# Generated by Django 3.1.5 on 2021-01-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('align_tap', '0003_auto_20210126_0733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='group',
        ),
        migrations.AddField(
            model_name='processedimagegroup',
            name='images',
            field=models.ManyToManyField(to='align_tap.ProcessedImage'),
        ),
    ]
