# Generated by Django 3.1.5 on 2021-01-26 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('align_tap', '0004_auto_20210126_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedimage',
            name='base',
        ),
        migrations.RemoveField(
            model_name='processedimage',
            name='user',
        ),
        migrations.AddField(
            model_name='processedimagegroup',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='align_tap.baseimage'),
        ),
    ]
